name: CI - Maven Docker

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
 
      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        if: ${{ contains( github.ref_name, 'master' ) }}
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Push to Aliyun Registry
        if: ${{ contains( github.ref_name, 'master' ) }}
        env:
          IMAGE_NAME: registry.cn-guangzhou.aliyuncs.com/archongum/postgres:14.4
        run: |
          # show size
          du -sh ./*
          # chmod +x
          chmod +x ./*.sh
          # build
          docker build -f Dockerfile --tag $IMAGE_NAME .
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME
